# Generated by Django 4.0.2 on 2022-03-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.CharField(choices=[('₽', '₽'), ('Договорная', 'Договорная')], default='₽', max_length=10),
        ),
    ]
