# Generated by Django 4.0.2 on 2022-03-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, default='default.svg', upload_to='website/static/images/media'),
        ),
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
