# Generated by Django 4.0.2 on 2022-03-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_card_currency_alter_card_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='currency',
            field=models.CharField(choices=[('₽', '₽'), ('Договорная', 'Договорная')], default='₽', max_length=10),
        ),
    ]
